# Generated by Django 3.2.16 on 2025-06-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_eng', models.CharField(max_length=100, verbose_name='Термин')),
                ('abbr_eng', models.CharField(max_length=100, verbose_name='Термин на английском')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('part_references', models.CharField(max_length=100, verbose_name='Часть речи')),
                ('term_rus', models.CharField(max_length=100, verbose_name='Термин на русском')),
                ('definition_rus', models.TextField(verbose_name='Определение на русском')),
                ('definition_eng', models.TextField(verbose_name='Определение на английском')),
                ('context_eng', models.TextField(verbose_name='Контекст на английском')),
                ('context_rus', models.TextField(verbose_name='Контекст на русском')),
            ],
        ),
    ]
